### ISSUE TITLE
Zepio not authorized to access rpc and passcode

### ISSUE THREAD

**Issue by Mobster2** [ZcashFoundation/zepio#152] opened 2019-06-11 14:07 UTC
Hello, Windows user here, I am using external zcashd that I run on ubuntu, when attempting to install zepio on ubuntu I receive the message: 
dpkg: error: cannot access archive 'zepio-linux-vX.X.X.deb': No such file or directory
I have downloaded the zepio.deb file. 
The only reason I ran external node to begin with is that Zepio did not run a daemon by default when I downloaded the windows version and I received the check logs error message. 
Thank you in advance for any help!

**Comment by guilhermedecampo** [comment] 2019-06-11 14:13
Hi @Mobster2! Thank you for your time to write here. 

First and foremost would be awesome to know more about your problem with windows version not running the daemon by default. So can you answer these questions?

### Environment

- What version of Zepio are you using?
- Which Operating System are you using (macOS/Linux/Windows)? What version?
- Are you using an external `zcashd` daemon or the one built inside Zepio?

### Logs

- `%APPDATA%/zepio/main-process-logs.txt` on Windows
- `$XDG_CONFIG_HOME/zepio/main-process-logs.txt` or `~/.config/zepio/main-process-logs.txt` on Linux
- `~/Library/Application Support/zepio/main-process-logs.txt` on macOS

**Comment by Mobster2** [comment] 2019-06-11 14:26
I am attempting to use v0.7.3 
using windows 10
using external zcashd (only because the one built inside Zepio did not run)

**Comment by Mobster2** [comment] 2019-06-11 14:39
Zepio says "not authorized to access rpc and password"

**Comment by andrerfneves** [comment] 2019-06-11 18:36
@Mobster2 could you post the logs that @guilhermedecampo mentioned above? We need to see what the application is attempting to do/connect with.

**Comment by ph0nky** [comment] 2019-06-12 22:55
Hey, having the same problem. I am running on Debian though. I do however get the same message
"Not authorized to access Zcash RPC, plese check your rpcuser and rpcpassword"
I am running the official zcashd node with a -datadir option in the commandline.

**Comment by georgelima** [comment] 2019-06-12 23:51
> Hello, Windows user here, I am using external zcashd that I run on ubuntu, when attempting to install zepio on ubuntu I receive the message:
> dpkg: error: cannot access archive 'zepio-linux-vX.X.X.deb': No such file or directory
> I have downloaded the zepio.deb file.
> The only reason I ran external node to begin with is that Zepio did not run a daemon by default when I downloaded the windows version and I received the check logs error message.
> Thank you in advance for any help!

@Mobster2 Do you have the `rpcuser` and `rpcpassword` defined in your zcash.conf?

> Hey, having the same problem. I am running on Debian though. I do however get the same message
> "Not authorized to access Zcash RPC, plese check your rpcuser and rpcpassword"
> I am running the official zcashd node with a -datadir option in the commandline.

@ph0nky Could you define `rpcuser` and `rpcpassword` also when running the daemon from the command line?

e.g: 
```bash
zcashd -datadir=CUSTOM/DATA/DIR -rpcuser="YOUR_USER" -rpcpassword="YOUR_PASSWORD"
```

**Comment by ph0nky** [comment] 2019-06-13 11:47
> > Hello, Windows user here, I am using external zcashd that I run on ubuntu, when attempting to install zepio on ubuntu I receive the message:
> > dpkg: error: cannot access archive 'zepio-linux-vX.X.X.deb': No such file or directory
> > I have downloaded the zepio.deb file.
> > The only reason I ran external node to begin with is that Zepio did not run a daemon by default when I downloaded the windows version and I received the check logs error message.
> > Thank you in advance for any help!
> 
> @Mobster2 Do you have the `rpcuser` and `rpcpassword` defined in your zcash.conf?
> 
> > Hey, having the same problem. I am running on Debian though. I do however get the same message
> > "Not authorized to access Zcash RPC, plese check your rpcuser and rpcpassword"
> > I am running the official zcashd node with a -datadir option in the commandline.
> 
> @ph0nky Could you define `rpcuser` and `rpcpassword` also when running the daemon from the command line?
> 
> e.g:
> 
> ```shell
> zcashd -datadir=CUSTOM/DATA/DIR -rpcuser="YOUR_USER" -rpcpassword="YOUR_PASSWORD"
> ```

I tried that and get in the terminal the following error: "Error: There is no RPC client functionality in zcashd. Use the zcash-cli utility instead."

**Comment by rex4539** [comment] 2019-06-14 18:02
Actually, I have the same bug on macOS when I start Zepio with `zcashd` already running.

**Comment by andrerfneves** [comment] 2019-06-18 01:48
@rex4539 did you get this resolved?

@Mobster2 could you make sure you have `server=1` in your zcash.conf to tell your node to allow RPC calls? Docks here: https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_conf_guide.html#json-rpc-options

**Comment by rex4539** [comment] 2019-06-21 19:04
@andrerfneves Nope.

![Screen Shot 2019-06-21 at 22 03 48](https://user-images.githubusercontent.com/227442/59945528-90e9cc00-9470-11e9-9852-f39b770952e4.png)

**Comment by guilhermedecampo** [comment] 2019-06-22 01:51
Can you please at least add more information instead of only saying "Nope" @rex4539?

**Comment by rex4539** [comment] 2019-06-22 10:35
1. `% zcashd --daemon`
2. Launch Zepio.

What happened:

![](https://user-images.githubusercontent.com/227442/59945528-90e9cc00-9470-11e9-9852-f39b770952e4.png)

Expected result:

![](https://raw.githubusercontent.com/ZcashFoundation/zepio-docs/develop/docz/assets/dashboard.png)

**Comment by andrerfneves** [comment] 2019-06-23 01:13
Did you try the aforementioned 'server=1' approach as well?

**Comment by rex4539** [comment] 2019-06-24 21:11
Same issue when `server=1` is defined.

**Comment by georgelima** [comment] 2019-06-24 22:38
Really weird @rex4539 , seems that Zepio couldn't find your RPC credentials (rpcuser and rpcpassword), do you ensure that they are set in your `zcash.conf` (or in the command line)?

**Comment by rex4539** [comment] 2019-06-24 23:18
They are set in `zcash.conf`

**Comment by georgelima** [comment] 2019-06-25 00:07
Ok, can you send me the content of your `zcash.conf`? (you can remove the content of your credentials)

So I can try to reproduce here, thanks!

**Comment by rex4539** [comment] 2019-06-25 05:06
```
addnode=mainnet.z.cash
addnode=zcmaintvsivr7pcn.onion
addnode=zcashiqykswlzpsu.onion
addnode=zcashqhrmju6zfhn.onion
addnode=zcashgmvxwrmjsut.onion
addnode=zcashz3uma65ix7b.onion
addnode=zcashiyf4kxluf3x.onion
addnode=zcashwfe4x3jkz2b.onion
addnode=zcashvkeki52iqpc.onion
addnode=zcasha3cmfrpy7b7.onion
addnode=zcashz7ed3nvbdxm.onion
addnode=zcash5adwfpxfuvf.onion
addnode=zcashixg5ol2ndo4.onion
addnode=zcashuzwa365oh3n.onion
addnode=zcashskbeoiwtym3.onion
addnode=zcashuyvk5e7qfzy.onion
addnode=fhsxfrwpyrtoxeal.onion
addnode=zcash2iihed2wdux.onion
addnode=w3dxku36wbp3lowx.onion
addnode=zcashuhmzycmlwld.onion
rpcuser=username
rpcpassword=mysupersecretpasswordhere
showmetrics=0
gen=0
proxy=127.0.0.1:9050
onlynet=onion
txindex=1
addressindex=1
timestampindex=1
spentindex=1
experimentalfeatures=1
paymentdisclosure=1
debug=paymentdisclosure
zmergetoaddress=1
insightexplorer=1
```

I run a Tor daemon locally and connect to the nodes via onion routing.

Just to note, ZecWallet has been working exceptionally well with this configuration so I don't see any reason why Zepio would have any issues :)

**Comment by georgelima** [comment] 2019-06-25 14:44
Trying here with the same approach (onion as proxy) and works perfectly, what version of the `zcashd` are you using?

**Comment by rex4539** [comment] 2019-06-25 14:46
Latest master.

**Comment by phideas** [comment] 2019-08-22 15:53
I had the same issue, solved by removing '=' character from my rpc password.

**Comment by andrerfneves** [comment] 2019-10-05 20:33
@phideas interesting. I'll try and debug further why `=` is. an issue. May be due to the decoding of the `conf` file which is expecting key/value pairs separated by `=` signs. Closing this for now.

**Closed by andrerfneves** 2019-10-05 20:33 UTC
